import { defineConfig, devices } from "@playwright/test"
import { fileURLToPath } from "url"
import path from "path"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

/**
 * Playwright E2E configuration for GadaiTop web app.
 *
 * Auth state files (auto-generated by auth.setup.ts, git-ignored):
 *   e2e/auth/admin-pt.json     → Admin PT session
 *   e2e/auth/staff-toko.json   → Staff Toko session
 *   e2e/auth/super-admin.json  → Super Admin session
 *
 * Commands:
 *   pnpm test:e2e              — run all tests (headless)
 *   pnpm test:e2e:ui           — interactive UI mode
 *   pnpm test:e2e:headed       — headed browser (watch it run)
 *   pnpm test:e2e:report       — open last HTML report
 *
 * Run with filter:
 *   pnpm test:e2e --grep "Setor Uang"
 *   pnpm test:e2e --grep "auth"
 */
export default defineConfig({
  testDir: "./e2e",
  testMatch: ["**/*.spec.ts", "**/auth.setup.ts"],

  // Run tests sequentially to avoid DB conflicts
  fullyParallel: false,
  workers: 1,

  // Fail the build on CI if you accidentally left test.only in the source code
  forbidOnly: !!process.env.CI,

  // Retry on CI only
  retries: process.env.CI ? 2 : 0,

  // Reporters
  reporter: [
    ["list"],
    ["html", { open: "never", outputFolder: "e2e/reports/html" }],
  ],

  // Output folder for traces, screenshots, videos
  outputDir: "e2e/test-results",

  use: {
    baseURL: "http://localhost:3000",

    // Collect trace on first retry
    trace: "on-first-retry",

    // Screenshot on failure
    screenshot: "only-on-failure",

    // Indonesian locale / WIB timezone
    locale: "id-ID",
    timezoneId: "Asia/Jakarta",

    // Default: no auth state — tests that need auth use test.use() in their describe block
    // See: e2e/specs/auth.spec.ts (no auth), setor-uang.spec.ts (role-based)
  },

  projects: [
    // ── 1. Run auth setup first ───────────────────────────────────────────────
    {
      name: "auth-setup",
      testMatch: /auth\.setup\.ts/,
      use: { ...devices["Desktop Chrome"] },
    },

    // ── 2. All feature tests — depend on auth setup ───────────────────────────
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
      dependencies: ["auth-setup"],
      testMatch: /specs\/.*\.spec\.ts/,
    },
  ],

  // Start both the API backend and Next.js frontend before running tests.
  // reuseExistingServer=true: if you already have them running in other
  // terminals, Playwright will skip starting new ones (fastest workflow).
  webServer: [
    {
      // NestJS API on port 8080 — start from the monorepo root
      command: "pnpm dev:api",
      url: "http://localhost:8080/api/v1/health",
      reuseExistingServer: true,
      timeout: 120_000,
      cwd: "../../", // monorepo root
    },
    {
      // Next.js frontend on port 3000
      command: "pnpm dev",
      url: "http://localhost:3000",
      reuseExistingServer: true,
      timeout: 120_000,
    },
  ],
})
