import { MigrationInterface, QueryRunner } from 'typeorm';

export class CustomerCatalogSpkNkbCashCapitalSOSchema1770097957509 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TYPE "public"."stock_opname_sessions_status_enum" AS ENUM('draft', 'in_progress', 'completed', 'approved')`);
    await queryRunner.query(`CREATE TABLE "stock_opname_sessions" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "session_code" character varying(50) NOT NULL, "pt_id" uuid NOT NULL, "store_id" uuid NOT NULL, "start_date" date NOT NULL, "end_date" date, "status" "public"."stock_opname_sessions_status_enum" NOT NULL DEFAULT 'draft', "total_items_system" integer NOT NULL DEFAULT '0', "total_items_counted" integer NOT NULL DEFAULT '0', "variances_count" integer NOT NULL DEFAULT '0', "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "notes" text, CONSTRAINT "UQ_88f6ab0fa9a505fa48ddc4c1fde" UNIQUE ("uuid"), CONSTRAINT "UQ_8d6973e484fd9cf1b8f772b89bc" UNIQUE ("session_code"), CONSTRAINT "PK_d88f04fc8b237f005a2978c90fb" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_8d6973e484fd9cf1b8f772b89b" ON "stock_opname_sessions" ("session_code") `);
    await queryRunner.query(`CREATE INDEX "IDX_158230d423f0571798abbc87e4" ON "stock_opname_sessions" ("pt_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_e9d8353a3e42e4284ad521fb95" ON "stock_opname_sessions" ("store_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_71a3caa9ff81a4a87a712b910c" ON "stock_opname_sessions" ("start_date") `);
    await queryRunner.query(`CREATE INDEX "IDX_156709091f5baa52bd7be0cedd" ON "stock_opname_sessions" ("status") `);
    await queryRunner.query(`CREATE TYPE "public"."stock_opname_items_condition_before_enum" AS ENUM('excellent', 'good', 'fair', 'poor')`);
    await queryRunner.query(`CREATE TYPE "public"."stock_opname_items_condition_after_enum" AS ENUM('excellent', 'good', 'fair', 'poor')`);
    await queryRunner.query(`CREATE TABLE "stock_opname_items" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "so_session_id" uuid NOT NULL, "spk_item_id" uuid NOT NULL, "system_quantity" integer NOT NULL DEFAULT '1', "counted_quantity" integer, "condition_before" "public"."stock_opname_items_condition_before_enum", "condition_after" "public"."stock_opname_items_condition_after_enum", "condition_notes" text, "damage_photos" jsonb, "counted_by" uuid, "counted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_89edf97027983a9682951168960" UNIQUE ("uuid"), CONSTRAINT "PK_dcc8e18859199c2b516750bba50" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_eb59399933b39fba064aedd376" ON "stock_opname_items" ("so_session_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_abeacf1eb60c52469858f1dd60" ON "stock_opname_items" ("spk_item_id") `);
    await queryRunner.query(`CREATE TYPE "public"."so_priority_rules_rule_type_enum" AS ENUM('item_type', 'value_threshold', 'days_overdue', 'custom')`);
    await queryRunner.query(`CREATE TABLE "so_priority_rules" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "pt_id" uuid NOT NULL, "rule_name" character varying(255) NOT NULL, "rule_type" "public"."so_priority_rules_rule_type_enum" NOT NULL, "rule_config" jsonb NOT NULL, "priority_level" smallint NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "description" text, CONSTRAINT "UQ_fee1770a516b95c64247db2f96b" UNIQUE ("uuid"), CONSTRAINT "PK_11a79950b444d0a12b59f1bc3bd" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_c11f074084a32a388da24f4b92" ON "so_priority_rules" ("pt_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_c06a34d2771c1e768cfd23a3c8" ON "so_priority_rules" ("priority_level") `);
    await queryRunner.query(`CREATE INDEX "IDX_0514736a597e88da065552e17e" ON "so_priority_rules" ("is_active") `);
    await queryRunner.query(`CREATE TYPE "public"."spk_items_condition_enum" AS ENUM('excellent', 'good', 'fair', 'poor')`);
    await queryRunner.query(`CREATE TYPE "public"."spk_items_status_enum" AS ENUM('in_storage', 'in_auction', 'sold', 'returned')`);
    await queryRunner.query(`CREATE TABLE "spk_items" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "spk_id" uuid NOT NULL, "catalog_id" uuid, "item_type_id" uuid NOT NULL, "description" text NOT NULL, "brand" character varying(100), "model" character varying(100), "serial_number" character varying(100), "appraised_value" numeric(15,2) NOT NULL, "condition" "public"."spk_items_condition_enum" NOT NULL DEFAULT 'good', "weight" numeric(10,3), "purity" character varying(20), "evidence_photos" jsonb, "storage_location" character varying(100), "qr_code" character varying(100), "status" "public"."spk_items_status_enum" NOT NULL DEFAULT 'in_storage', CONSTRAINT "UQ_7c4842b3f324be6c48fd3ca373a" UNIQUE ("uuid"), CONSTRAINT "UQ_9dd3c1b7a293ec6d739ea3ba251" UNIQUE ("qr_code"), CONSTRAINT "PK_f9f089c1d8ac109543ea30c67ff" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_fa5cfbee7fb098b6acd3a9f5b1" ON "spk_items" ("spk_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_745f64916b553bc3f9ace401ed" ON "spk_items" ("catalog_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_a43ff2adf5e3c16595c1c59623" ON "spk_items" ("item_type_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_b11dee211a855bd449bbd9f46e" ON "spk_items" ("condition") `);
    await queryRunner.query(`CREATE INDEX "IDX_9dd3c1b7a293ec6d739ea3ba25" ON "spk_items" ("qr_code") `);
    await queryRunner.query(`CREATE INDEX "IDX_ae048967544ffd51a09861c803" ON "spk_items" ("status") `);
    await queryRunner.query(`CREATE TABLE "pawn_terms" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "pt_id" uuid NOT NULL, "item_type_id" uuid NOT NULL, "loan_limit_min" numeric(15,2) NOT NULL, "loan_limit_max" numeric(15,2) NOT NULL, "tenor_default" integer NOT NULL, "interest_rate" numeric(5,2) NOT NULL, "admin_fee" numeric(15,2) NOT NULL DEFAULT '0', CONSTRAINT "UQ_c3d7fe1b1cbe2a7b891c8f22f35" UNIQUE ("uuid"), CONSTRAINT "UQ_b30a5bf9c87f26da179d68859ed" UNIQUE ("pt_id", "item_type_id"), CONSTRAINT "PK_770109026cadbcb553e8280dfcf" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_b301dc3e9be817e0ac818ca47f" ON "pawn_terms" ("pt_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_78eb4db269102a242738aac349" ON "pawn_terms" ("item_type_id") `);
    await queryRunner.query(`CREATE TYPE "public"."nkb_records_payment_type_enum" AS ENUM('renewal', 'partial', 'full_redemption')`);
    await queryRunner.query(`CREATE TYPE "public"."nkb_records_payment_method_enum" AS ENUM('cash', 'transfer', 'qris', 'virtual_account')`);
    await queryRunner.query(`CREATE TYPE "public"."nkb_records_status_enum" AS ENUM('pending', 'confirmed', 'rejected', 'failed')`);
    await queryRunner.query(`CREATE TABLE "nkb_records" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "nkb_number" character varying(50) NOT NULL, "spk_id" uuid NOT NULL, "amount_paid" numeric(15,2) NOT NULL, "payment_type" "public"."nkb_records_payment_type_enum" NOT NULL, "payment_method" "public"."nkb_records_payment_method_enum" NOT NULL, "payment_proof_url" character varying(500), "transaction_ref" character varying(100), "status" "public"."nkb_records_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "confirmed_by" uuid, "confirmed_at" TIMESTAMP WITH TIME ZONE, "rejection_reason" text, "is_customer_initiated" boolean NOT NULL DEFAULT false, "payment_gateway_provider" character varying(50), "payment_gateway_order_id" character varying(100), "payment_gateway_status" character varying(50), "payment_gateway_callback_data" jsonb, "expires_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_befa71521f631386b099d722988" UNIQUE ("uuid"), CONSTRAINT "UQ_522133c224d7bee558e29863771" UNIQUE ("nkb_number"), CONSTRAINT "PK_c57160ffa3e0d89f8e3dd16ddbc" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_522133c224d7bee558e2986377" ON "nkb_records" ("nkb_number") `);
    await queryRunner.query(`CREATE INDEX "IDX_f31c6162794fd776514807dafc" ON "nkb_records" ("spk_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_881b29bfdd228c11921c4c40e3" ON "nkb_records" ("payment_type") `);
    await queryRunner.query(`CREATE INDEX "IDX_8a4c84e33758cf26f5bb06e5ab" ON "nkb_records" ("status") `);
    await queryRunner.query(`CREATE INDEX "IDX_3be5feac52d178dcc5dbeef0c3" ON "nkb_records" ("payment_gateway_order_id") `);
    await queryRunner.query(`CREATE TYPE "public"."customers_gender_enum" AS ENUM('male', 'female')`);
    await queryRunner.query(`CREATE TABLE "customers" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "nik" character varying(20) NOT NULL, "pin_hash" character varying(255) NOT NULL, "password_hash" character varying(255), "name" character varying(255) NOT NULL, "dob" date NOT NULL, "gender" "public"."customers_gender_enum" NOT NULL, "address" text NOT NULL, "city" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "email" character varying(255) NOT NULL, "ktp_photo_url" character varying(500), "selfie_photo_url" character varying(500), "pt_id" uuid NOT NULL, "is_blacklisted" boolean NOT NULL DEFAULT false, "blacklisted_at" TIMESTAMP WITH TIME ZONE, "blacklisted_by" uuid, "blacklist_reason" text, "unblacklisted_at" TIMESTAMP WITH TIME ZONE, "unblacklisted_by" uuid, CONSTRAINT "UQ_a41cc8fde9ac3d9bcb91412c596" UNIQUE ("uuid"), CONSTRAINT "UQ_14e5b41d4cdfb088f3e02bce93e" UNIQUE ("nik"), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_14e5b41d4cdfb088f3e02bce93" ON "customers" ("nik") `);
    await queryRunner.query(`CREATE INDEX "IDX_b942d55b92ededa770041db9de" ON "customers" ("name") `);
    await queryRunner.query(`CREATE INDEX "IDX_1d497ab89fbba95db7a464ed57" ON "customers" ("city") `);
    await queryRunner.query(`CREATE INDEX "IDX_88acd889fbe17d0e16cc4bc917" ON "customers" ("phone") `);
    await queryRunner.query(`CREATE INDEX "IDX_8536b8b85c06969f84f0c098b0" ON "customers" ("email") `);
    await queryRunner.query(`CREATE INDEX "IDX_9bef4b29503faff08a40198a46" ON "customers" ("pt_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_d2641b18287fab5549f410c8fb" ON "customers" ("is_blacklisted") `);
    await queryRunner.query(`CREATE TABLE "customer_pin_history" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "customer_id" uuid NOT NULL, "old_pin_hash" character varying(255), "new_pin_hash" character varying(255) NOT NULL, "changed_by" uuid, "change_reason" character varying(255), "ip_address" inet, "user_agent" text, CONSTRAINT "UQ_2e88ef13f3b6dace64a2f648879" UNIQUE ("uuid"), CONSTRAINT "PK_9d13198a48863569636bfa8374b" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_3fba764534e2668eb43b1f1e66" ON "customer_pin_history" ("customer_id") `);
    await queryRunner.query(`CREATE TABLE "catalogs" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "code" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "pt_id" uuid NOT NULL, "item_type_id" uuid NOT NULL, "base_price" numeric(15,2) NOT NULL, "pawn_value_min" numeric(15,2) NOT NULL, "pawn_value_max" numeric(15,2) NOT NULL, "tenor_options" jsonb, "description" text, CONSTRAINT "UQ_ba681f4a6abbc691cde3506a67e" UNIQUE ("uuid"), CONSTRAINT "UQ_dd5ceb9fa629fcb0793520d31b6" UNIQUE ("pt_id", "code"), CONSTRAINT "PK_1883399275415ee6107413fe6c3" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_6a643db5f766fcb64f213a20b0" ON "catalogs" ("name") `);
    await queryRunner.query(`CREATE INDEX "IDX_bd94c827e1c6876164acb2d399" ON "catalogs" ("pt_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_ffdf6e247b214c02bc94ae5b9b" ON "catalogs" ("item_type_id") `);
    await queryRunner.query(`CREATE TYPE "public"."spk_records_status_enum" AS ENUM('draft', 'active', 'extended', 'redeemed', 'overdue', 'auctioned', 'closed')`);
    await queryRunner.query(`CREATE TABLE "spk_records" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "spk_number" character varying(50) NOT NULL, "internal_spk_number" character varying(20), "customer_spk_number" character varying(20), "customer_id" uuid NOT NULL, "store_id" uuid NOT NULL, "pt_id" uuid NOT NULL, "principal_amount" numeric(15,2) NOT NULL, "tenor" integer NOT NULL, "interest_rate" numeric(5,2) NOT NULL, "admin_fee" numeric(15,2) NOT NULL DEFAULT '0', "total_amount" numeric(15,2) NOT NULL, "remaining_balance" numeric(15,2) NOT NULL, "due_date" date NOT NULL, "status" "public"."spk_records_status_enum" NOT NULL DEFAULT 'draft', "confirmed_at" TIMESTAMP WITH TIME ZONE, "confirmed_by_pin" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_685931a3ac54273a808252c8f42" UNIQUE ("uuid"), CONSTRAINT "UQ_e78e9eb788a8049c6439f440fe6" UNIQUE ("spk_number"), CONSTRAINT "UQ_ea93727c5228bdfe2c02068bc65" UNIQUE ("internal_spk_number"), CONSTRAINT "UQ_d803f37164b25592c0db620794f" UNIQUE ("customer_spk_number"), CONSTRAINT "PK_9a522b160232f75d0afcc8c8d96" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_e78e9eb788a8049c6439f440fe" ON "spk_records" ("spk_number") `);
    await queryRunner.query(`CREATE INDEX "IDX_ea93727c5228bdfe2c02068bc6" ON "spk_records" ("internal_spk_number") `);
    await queryRunner.query(`CREATE INDEX "IDX_d803f37164b25592c0db620794" ON "spk_records" ("customer_spk_number") `);
    await queryRunner.query(`CREATE INDEX "IDX_e33e5bceda2aec2adfbfa7ffa4" ON "spk_records" ("customer_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_b811b018e84be20e7d80c4e51f" ON "spk_records" ("store_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_0031a64273aeeb268b97d7fadc" ON "spk_records" ("pt_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_f9fc0ee896a7d61af019b37e4e" ON "spk_records" ("due_date") `);
    await queryRunner.query(`CREATE INDEX "IDX_9f153a2e88fd5c53d97d9b2029" ON "spk_records" ("status") `);
    await queryRunner.query(`CREATE TABLE "catalog_price_history" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "catalog_id" uuid NOT NULL, "base_price" numeric(15,2) NOT NULL, "pawn_value_min" numeric(15,2) NOT NULL, "pawn_value_max" numeric(15,2) NOT NULL, "effective_from" date NOT NULL, "effective_until" date, "change_reason" text, CONSTRAINT "UQ_478a908c49179b3191e76fc94cd" UNIQUE ("uuid"), CONSTRAINT "PK_65e575f8725c2641f81974b2375" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_d01227a10f725767871b0c9d70" ON "catalog_price_history" ("catalog_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_f8adeeeaa64569308ac870ee9b" ON "catalog_price_history" ("effective_from") `);
    await queryRunner.query(`CREATE INDEX "IDX_f2144e1ef8a9e2a3554857e473" ON "catalog_price_history" ("effective_until") `);
    await queryRunner.query(`CREATE TYPE "public"."cash_deposits_payment_method_enum" AS ENUM('bank_transfer', 'qris', 'virtual_account')`);
    await queryRunner.query(`CREATE TYPE "public"."cash_deposits_status_enum" AS ENUM('pending', 'paid', 'confirmed', 'rejected', 'expired')`);
    await queryRunner.query(`CREATE TABLE "cash_deposits" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "deposit_code" character varying(50) NOT NULL, "store_id" uuid NOT NULL, "pt_id" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "payment_method" "public"."cash_deposits_payment_method_enum" NOT NULL, "payment_channel" character varying(100), "qr_code_url" character varying(500), "virtual_account" character varying(50), "payment_proof_url" character varying(500), "status" "public"."cash_deposits_status_enum" NOT NULL DEFAULT 'pending', "requested_by" uuid NOT NULL, "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "notes" text, "rejection_reason" text, CONSTRAINT "UQ_f413648c0b0cc4dfe400ec34c30" UNIQUE ("uuid"), CONSTRAINT "UQ_b830f574134adbdbc6af436333e" UNIQUE ("deposit_code"), CONSTRAINT "PK_c05034891f3240aff6551ae6993" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_b830f574134adbdbc6af436333" ON "cash_deposits" ("deposit_code") `);
    await queryRunner.query(`CREATE INDEX "IDX_f59ec7413da98e2350e3c2d9ba" ON "cash_deposits" ("store_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_e3fe996b38001deb47f4b0dfee" ON "cash_deposits" ("pt_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_d07846b169228f6b5b0d4dbd88" ON "cash_deposits" ("status") `);
    await queryRunner.query(`CREATE TYPE "public"."cash_mutations_mutation_type_enum" AS ENUM('debit', 'credit', 'adjustment')`);
    await queryRunner.query(`CREATE TYPE "public"."cash_mutations_category_enum" AS ENUM('spk_disbursement', 'nkb_payment', 'deposit', 'topup', 'expense', 'other')`);
    await queryRunner.query(`CREATE TABLE "cash_mutations" ("id" SERIAL NOT NULL, "store_id" uuid NOT NULL, "mutation_date" date NOT NULL, "mutation_type" "public"."cash_mutations_mutation_type_enum" NOT NULL, "category" "public"."cash_mutations_category_enum" NOT NULL, "amount" numeric(15,2) NOT NULL, "balance_before" numeric(15,2) NOT NULL, "balance_after" numeric(15,2) NOT NULL, "description" text, "reference_type" character varying(50), "reference_id" character varying(36), "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7047955078e67c011abec81b039" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_a02a3e482ddcedb5992c4513d1" ON "cash_mutations" ("store_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_4b5d4551dab9044a8d85d23bc2" ON "cash_mutations" ("mutation_date") `);
    await queryRunner.query(`CREATE INDEX "IDX_a35665e6fab2369fac53715aa3" ON "cash_mutations" ("mutation_type") `);
    await queryRunner.query(`CREATE INDEX "IDX_68ddc03fe465bb8d36045e8173" ON "cash_mutations" ("category") `);
    await queryRunner.query(`CREATE TYPE "public"."capital_topups_status_enum" AS ENUM('pending', 'approved', 'rejected', 'disbursed')`);
    await queryRunner.query(`CREATE TABLE "capital_topups" ("id" SERIAL NOT NULL, "uuid" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "version" integer NOT NULL, "created_by" uuid, "updated_by" uuid, "deleted_by" uuid, "topup_code" character varying(50) NOT NULL, "store_id" uuid NOT NULL, "pt_id" uuid NOT NULL, "amount" numeric(15,2) NOT NULL, "reason" text NOT NULL, "status" "public"."capital_topups_status_enum" NOT NULL DEFAULT 'pending', "requested_by" uuid NOT NULL, "approved_by" uuid, "approved_at" TIMESTAMP WITH TIME ZONE, "disbursed_at" TIMESTAMP WITH TIME ZONE, "disbursement_proof_url" character varying(500), "notes" text, "rejection_reason" text, CONSTRAINT "UQ_00946ce28e138cb6994d1ed1ff7" UNIQUE ("uuid"), CONSTRAINT "UQ_be46cca9d9bd3867b6fd8e815b4" UNIQUE ("topup_code"), CONSTRAINT "PK_f9b4747fd2cd40111363fc25851" PRIMARY KEY ("id"))`);
    await queryRunner.query(`CREATE INDEX "IDX_be46cca9d9bd3867b6fd8e815b" ON "capital_topups" ("topup_code") `);
    await queryRunner.query(`CREATE INDEX "IDX_e3e8c1f0249a5820aae9872e0f" ON "capital_topups" ("store_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_864f6c08b6e694bf8a960500e2" ON "capital_topups" ("pt_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_d68a7847b05bf5b181e5e9d950" ON "capital_topups" ("status") `);
    await queryRunner.query(`ALTER TABLE "stock_opname_sessions" ADD CONSTRAINT "FK_158230d423f0571798abbc87e41" FOREIGN KEY ("pt_id") REFERENCES "companies"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_sessions" ADD CONSTRAINT "FK_e9d8353a3e42e4284ad521fb95e" FOREIGN KEY ("store_id") REFERENCES "branches"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_sessions" ADD CONSTRAINT "FK_49a57612b08de98d31a17597630" FOREIGN KEY ("created_by") REFERENCES "users"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_sessions" ADD CONSTRAINT "FK_ba6fc03a88223278dbec9e4a93d" FOREIGN KEY ("approved_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_items" ADD CONSTRAINT "FK_eb59399933b39fba064aedd3768" FOREIGN KEY ("so_session_id") REFERENCES "stock_opname_sessions"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_items" ADD CONSTRAINT "FK_abeacf1eb60c52469858f1dd60e" FOREIGN KEY ("spk_item_id") REFERENCES "spk_items"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_items" ADD CONSTRAINT "FK_83bdb0be7a481959ec593ff1964" FOREIGN KEY ("counted_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "so_priority_rules" ADD CONSTRAINT "FK_c11f074084a32a388da24f4b922" FOREIGN KEY ("pt_id") REFERENCES "companies"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "spk_items" ADD CONSTRAINT "FK_fa5cfbee7fb098b6acd3a9f5b1c" FOREIGN KEY ("spk_id") REFERENCES "spk_records"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "spk_items" ADD CONSTRAINT "FK_745f64916b553bc3f9ace401ed5" FOREIGN KEY ("catalog_id") REFERENCES "catalogs"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "spk_items" ADD CONSTRAINT "FK_a43ff2adf5e3c16595c1c596236" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "pawn_terms" ADD CONSTRAINT "FK_b301dc3e9be817e0ac818ca47f4" FOREIGN KEY ("pt_id") REFERENCES "companies"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "pawn_terms" ADD CONSTRAINT "FK_78eb4db269102a242738aac3495" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "nkb_records" ADD CONSTRAINT "FK_f31c6162794fd776514807dafc6" FOREIGN KEY ("spk_id") REFERENCES "spk_records"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "nkb_records" ADD CONSTRAINT "FK_dc399574fcb95a3230f5dc73a11" FOREIGN KEY ("created_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "nkb_records" ADD CONSTRAINT "FK_fa80122a78e9eeb915586ac8904" FOREIGN KEY ("confirmed_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_9bef4b29503faff08a40198a463" FOREIGN KEY ("pt_id") REFERENCES "companies"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_8f138f284609b045dc64c91757a" FOREIGN KEY ("created_by") REFERENCES "users"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_4a59f6cf71d8fd352911c01d8a1" FOREIGN KEY ("blacklisted_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_9970be4dc4c20d3a44bbcb0873d" FOREIGN KEY ("unblacklisted_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "customer_pin_history" ADD CONSTRAINT "FK_3fba764534e2668eb43b1f1e667" FOREIGN KEY ("customer_id") REFERENCES "customers"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "customer_pin_history" ADD CONSTRAINT "FK_d8222c589af34cd09ef59bf99b3" FOREIGN KEY ("changed_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "catalogs" ADD CONSTRAINT "FK_bd94c827e1c6876164acb2d399f" FOREIGN KEY ("pt_id") REFERENCES "companies"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "catalogs" ADD CONSTRAINT "FK_ffdf6e247b214c02bc94ae5b9b0" FOREIGN KEY ("item_type_id") REFERENCES "item_types"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "spk_records" ADD CONSTRAINT "FK_e33e5bceda2aec2adfbfa7ffa42" FOREIGN KEY ("customer_id") REFERENCES "customers"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "spk_records" ADD CONSTRAINT "FK_b811b018e84be20e7d80c4e51fe" FOREIGN KEY ("store_id") REFERENCES "branches"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "spk_records" ADD CONSTRAINT "FK_0031a64273aeeb268b97d7fadc6" FOREIGN KEY ("pt_id") REFERENCES "companies"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "catalog_price_history" ADD CONSTRAINT "FK_d01227a10f725767871b0c9d704" FOREIGN KEY ("catalog_id") REFERENCES "catalogs"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "catalog_price_history" ADD CONSTRAINT "FK_a634d2dbe17cab004a0ca0db5d3" FOREIGN KEY ("created_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "cash_deposits" ADD CONSTRAINT "FK_f59ec7413da98e2350e3c2d9baa" FOREIGN KEY ("store_id") REFERENCES "branches"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "cash_deposits" ADD CONSTRAINT "FK_e3fe996b38001deb47f4b0dfeed" FOREIGN KEY ("pt_id") REFERENCES "companies"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "cash_deposits" ADD CONSTRAINT "FK_56a0740b06a68961d1b2e80c78d" FOREIGN KEY ("requested_by") REFERENCES "users"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "cash_deposits" ADD CONSTRAINT "FK_bc0b22dd1e1303da55b2400e46e" FOREIGN KEY ("approved_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "cash_mutations" ADD CONSTRAINT "FK_a02a3e482ddcedb5992c4513d1a" FOREIGN KEY ("store_id") REFERENCES "branches"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "cash_mutations" ADD CONSTRAINT "FK_7724a474876bc53c32a0d948e98" FOREIGN KEY ("created_by") REFERENCES "users"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "capital_topups" ADD CONSTRAINT "FK_e3e8c1f0249a5820aae9872e0f1" FOREIGN KEY ("store_id") REFERENCES "branches"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "capital_topups" ADD CONSTRAINT "FK_864f6c08b6e694bf8a960500e2c" FOREIGN KEY ("pt_id") REFERENCES "companies"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "capital_topups" ADD CONSTRAINT "FK_1b42644febb544817a00d87d716" FOREIGN KEY ("requested_by") REFERENCES "users"("uuid") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "capital_topups" ADD CONSTRAINT "FK_ab6c9105b6b189b4985c0ecab7a" FOREIGN KEY ("approved_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "capital_topups" DROP CONSTRAINT "FK_ab6c9105b6b189b4985c0ecab7a"`);
    await queryRunner.query(`ALTER TABLE "capital_topups" DROP CONSTRAINT "FK_1b42644febb544817a00d87d716"`);
    await queryRunner.query(`ALTER TABLE "capital_topups" DROP CONSTRAINT "FK_864f6c08b6e694bf8a960500e2c"`);
    await queryRunner.query(`ALTER TABLE "capital_topups" DROP CONSTRAINT "FK_e3e8c1f0249a5820aae9872e0f1"`);
    await queryRunner.query(`ALTER TABLE "cash_mutations" DROP CONSTRAINT "FK_7724a474876bc53c32a0d948e98"`);
    await queryRunner.query(`ALTER TABLE "cash_mutations" DROP CONSTRAINT "FK_a02a3e482ddcedb5992c4513d1a"`);
    await queryRunner.query(`ALTER TABLE "cash_deposits" DROP CONSTRAINT "FK_bc0b22dd1e1303da55b2400e46e"`);
    await queryRunner.query(`ALTER TABLE "cash_deposits" DROP CONSTRAINT "FK_56a0740b06a68961d1b2e80c78d"`);
    await queryRunner.query(`ALTER TABLE "cash_deposits" DROP CONSTRAINT "FK_e3fe996b38001deb47f4b0dfeed"`);
    await queryRunner.query(`ALTER TABLE "cash_deposits" DROP CONSTRAINT "FK_f59ec7413da98e2350e3c2d9baa"`);
    await queryRunner.query(`ALTER TABLE "catalog_price_history" DROP CONSTRAINT "FK_a634d2dbe17cab004a0ca0db5d3"`);
    await queryRunner.query(`ALTER TABLE "catalog_price_history" DROP CONSTRAINT "FK_d01227a10f725767871b0c9d704"`);
    await queryRunner.query(`ALTER TABLE "spk_records" DROP CONSTRAINT "FK_0031a64273aeeb268b97d7fadc6"`);
    await queryRunner.query(`ALTER TABLE "spk_records" DROP CONSTRAINT "FK_b811b018e84be20e7d80c4e51fe"`);
    await queryRunner.query(`ALTER TABLE "spk_records" DROP CONSTRAINT "FK_e33e5bceda2aec2adfbfa7ffa42"`);
    await queryRunner.query(`ALTER TABLE "catalogs" DROP CONSTRAINT "FK_ffdf6e247b214c02bc94ae5b9b0"`);
    await queryRunner.query(`ALTER TABLE "catalogs" DROP CONSTRAINT "FK_bd94c827e1c6876164acb2d399f"`);
    await queryRunner.query(`ALTER TABLE "customer_pin_history" DROP CONSTRAINT "FK_d8222c589af34cd09ef59bf99b3"`);
    await queryRunner.query(`ALTER TABLE "customer_pin_history" DROP CONSTRAINT "FK_3fba764534e2668eb43b1f1e667"`);
    await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_9970be4dc4c20d3a44bbcb0873d"`);
    await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_4a59f6cf71d8fd352911c01d8a1"`);
    await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_8f138f284609b045dc64c91757a"`);
    await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_9bef4b29503faff08a40198a463"`);
    await queryRunner.query(`ALTER TABLE "nkb_records" DROP CONSTRAINT "FK_fa80122a78e9eeb915586ac8904"`);
    await queryRunner.query(`ALTER TABLE "nkb_records" DROP CONSTRAINT "FK_dc399574fcb95a3230f5dc73a11"`);
    await queryRunner.query(`ALTER TABLE "nkb_records" DROP CONSTRAINT "FK_f31c6162794fd776514807dafc6"`);
    await queryRunner.query(`ALTER TABLE "pawn_terms" DROP CONSTRAINT "FK_78eb4db269102a242738aac3495"`);
    await queryRunner.query(`ALTER TABLE "pawn_terms" DROP CONSTRAINT "FK_b301dc3e9be817e0ac818ca47f4"`);
    await queryRunner.query(`ALTER TABLE "spk_items" DROP CONSTRAINT "FK_a43ff2adf5e3c16595c1c596236"`);
    await queryRunner.query(`ALTER TABLE "spk_items" DROP CONSTRAINT "FK_745f64916b553bc3f9ace401ed5"`);
    await queryRunner.query(`ALTER TABLE "spk_items" DROP CONSTRAINT "FK_fa5cfbee7fb098b6acd3a9f5b1c"`);
    await queryRunner.query(`ALTER TABLE "so_priority_rules" DROP CONSTRAINT "FK_c11f074084a32a388da24f4b922"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_items" DROP CONSTRAINT "FK_83bdb0be7a481959ec593ff1964"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_items" DROP CONSTRAINT "FK_abeacf1eb60c52469858f1dd60e"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_items" DROP CONSTRAINT "FK_eb59399933b39fba064aedd3768"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_sessions" DROP CONSTRAINT "FK_ba6fc03a88223278dbec9e4a93d"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_sessions" DROP CONSTRAINT "FK_49a57612b08de98d31a17597630"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_sessions" DROP CONSTRAINT "FK_e9d8353a3e42e4284ad521fb95e"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_sessions" DROP CONSTRAINT "FK_158230d423f0571798abbc87e41"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_d68a7847b05bf5b181e5e9d950"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_864f6c08b6e694bf8a960500e2"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_e3e8c1f0249a5820aae9872e0f"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_be46cca9d9bd3867b6fd8e815b"`);
    await queryRunner.query(`DROP TABLE "capital_topups"`);
    await queryRunner.query(`DROP TYPE "public"."capital_topups_status_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_68ddc03fe465bb8d36045e8173"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_a35665e6fab2369fac53715aa3"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_4b5d4551dab9044a8d85d23bc2"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_a02a3e482ddcedb5992c4513d1"`);
    await queryRunner.query(`DROP TABLE "cash_mutations"`);
    await queryRunner.query(`DROP TYPE "public"."cash_mutations_category_enum"`);
    await queryRunner.query(`DROP TYPE "public"."cash_mutations_mutation_type_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_d07846b169228f6b5b0d4dbd88"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_e3fe996b38001deb47f4b0dfee"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_f59ec7413da98e2350e3c2d9ba"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_b830f574134adbdbc6af436333"`);
    await queryRunner.query(`DROP TABLE "cash_deposits"`);
    await queryRunner.query(`DROP TYPE "public"."cash_deposits_status_enum"`);
    await queryRunner.query(`DROP TYPE "public"."cash_deposits_payment_method_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_f2144e1ef8a9e2a3554857e473"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_f8adeeeaa64569308ac870ee9b"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_d01227a10f725767871b0c9d70"`);
    await queryRunner.query(`DROP TABLE "catalog_price_history"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_9f153a2e88fd5c53d97d9b2029"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_f9fc0ee896a7d61af019b37e4e"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_0031a64273aeeb268b97d7fadc"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_b811b018e84be20e7d80c4e51f"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_e33e5bceda2aec2adfbfa7ffa4"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_d803f37164b25592c0db620794"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_ea93727c5228bdfe2c02068bc6"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_e78e9eb788a8049c6439f440fe"`);
    await queryRunner.query(`DROP TABLE "spk_records"`);
    await queryRunner.query(`DROP TYPE "public"."spk_records_status_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_ffdf6e247b214c02bc94ae5b9b"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_bd94c827e1c6876164acb2d399"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_6a643db5f766fcb64f213a20b0"`);
    await queryRunner.query(`DROP TABLE "catalogs"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_3fba764534e2668eb43b1f1e66"`);
    await queryRunner.query(`DROP TABLE "customer_pin_history"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_d2641b18287fab5549f410c8fb"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_9bef4b29503faff08a40198a46"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_8536b8b85c06969f84f0c098b0"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_88acd889fbe17d0e16cc4bc917"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_1d497ab89fbba95db7a464ed57"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_b942d55b92ededa770041db9de"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_14e5b41d4cdfb088f3e02bce93"`);
    await queryRunner.query(`DROP TABLE "customers"`);
    await queryRunner.query(`DROP TYPE "public"."customers_gender_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_3be5feac52d178dcc5dbeef0c3"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_8a4c84e33758cf26f5bb06e5ab"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_881b29bfdd228c11921c4c40e3"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_f31c6162794fd776514807dafc"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_522133c224d7bee558e2986377"`);
    await queryRunner.query(`DROP TABLE "nkb_records"`);
    await queryRunner.query(`DROP TYPE "public"."nkb_records_status_enum"`);
    await queryRunner.query(`DROP TYPE "public"."nkb_records_payment_method_enum"`);
    await queryRunner.query(`DROP TYPE "public"."nkb_records_payment_type_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_78eb4db269102a242738aac349"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_b301dc3e9be817e0ac818ca47f"`);
    await queryRunner.query(`DROP TABLE "pawn_terms"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_ae048967544ffd51a09861c803"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_9dd3c1b7a293ec6d739ea3ba25"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_b11dee211a855bd449bbd9f46e"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_a43ff2adf5e3c16595c1c59623"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_745f64916b553bc3f9ace401ed"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_fa5cfbee7fb098b6acd3a9f5b1"`);
    await queryRunner.query(`DROP TABLE "spk_items"`);
    await queryRunner.query(`DROP TYPE "public"."spk_items_status_enum"`);
    await queryRunner.query(`DROP TYPE "public"."spk_items_condition_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_0514736a597e88da065552e17e"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_c06a34d2771c1e768cfd23a3c8"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_c11f074084a32a388da24f4b92"`);
    await queryRunner.query(`DROP TABLE "so_priority_rules"`);
    await queryRunner.query(`DROP TYPE "public"."so_priority_rules_rule_type_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_abeacf1eb60c52469858f1dd60"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_eb59399933b39fba064aedd376"`);
    await queryRunner.query(`DROP TABLE "stock_opname_items"`);
    await queryRunner.query(`DROP TYPE "public"."stock_opname_items_condition_after_enum"`);
    await queryRunner.query(`DROP TYPE "public"."stock_opname_items_condition_before_enum"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_156709091f5baa52bd7be0cedd"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_71a3caa9ff81a4a87a712b910c"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_e9d8353a3e42e4284ad521fb95"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_158230d423f0571798abbc87e4"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_8d6973e484fd9cf1b8f772b89b"`);
    await queryRunner.query(`DROP TABLE "stock_opname_sessions"`);
    await queryRunner.query(`DROP TYPE "public"."stock_opname_sessions_status_enum"`);
  }
}
