import { MigrationInterface, QueryRunner } from 'typeorm';

export class NewMigration1773904269101 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" DROP CONSTRAINT "FK_sos_assignees_user"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" DROP CONSTRAINT "FK_sos_assignees_session"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" DROP CONSTRAINT "FK_sos_pawn_terms_pawn_term"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" DROP CONSTRAINT "FK_sos_pawn_terms_session"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" DROP CONSTRAINT "FK_sos_stores_store"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" DROP CONSTRAINT "FK_sos_stores_session"`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" DROP CONSTRAINT "FK_auction_batch_assignees_user"`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" DROP CONSTRAINT "FK_auction_batch_assignees_batch"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_assignees_session"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_assignees_user"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_assignees_session_user"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_pawn_terms_session"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_pawn_terms_pawn_term"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_pawn_terms_session_pawn_term"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_stores_session"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_stores_store"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_sos_stores_session_store"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_auction_batch_assignees_batch"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_auction_batch_assignees_user"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_branches_branch_code_not_deleted"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_branches_company_branch_code_not_deleted"`);
    await queryRunner.query(`ALTER TABLE "spk_records" ADD "insurance_fee" numeric(15,2) NOT NULL DEFAULT '0'`);
    await queryRunner.query(`ALTER TABLE "spk_items" ADD "qr_code_printed_at" TIMESTAMP WITH TIME ZONE`);
    await queryRunner.query(`ALTER TABLE "spk_items" ADD "qr_code_print_count" integer NOT NULL DEFAULT '0'`);
    await queryRunner.query(`ALTER TABLE "nkb_records" ADD "insurance_fee" numeric(15,2) NOT NULL DEFAULT '0'`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" ALTER COLUMN "so_session_id" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" ALTER COLUMN "user_id" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" ALTER COLUMN "so_session_id" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" ALTER COLUMN "pawn_term_id" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" ALTER COLUMN "so_session_id" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" ALTER COLUMN "store_id" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ALTER COLUMN "version" DROP DEFAULT`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ALTER COLUMN "auction_batch_id" DROP NOT NULL`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ALTER COLUMN "user_id" DROP NOT NULL`);
    await queryRunner.query(`CREATE INDEX "IDX_c500a38998f9797629996f2a87" ON "stock_opname_session_assignees" ("id") `);
    await queryRunner.query(`CREATE INDEX "IDX_257cccf4450bda5f31c28dd87c" ON "stock_opname_session_assignees" ("uuid") `);
    await queryRunner.query(`CREATE INDEX "IDX_e30d49bab27136da3ecefaff75" ON "stock_opname_session_assignees" ("created_at") `);
    await queryRunner.query(`CREATE INDEX "IDX_0bbd27131fdab58209de4e4d79" ON "stock_opname_session_pawn_terms" ("id") `);
    await queryRunner.query(`CREATE INDEX "IDX_5cbeee10e4650f39fca87f8b72" ON "stock_opname_session_pawn_terms" ("uuid") `);
    await queryRunner.query(`CREATE INDEX "IDX_fdda08535272ae4e96015f5c0a" ON "stock_opname_session_pawn_terms" ("created_at") `);
    await queryRunner.query(`CREATE INDEX "IDX_caf5e1528bcd63f4a4124355b3" ON "stock_opname_session_stores" ("id") `);
    await queryRunner.query(`CREATE INDEX "IDX_dd59cce16448f08609fdb8f5ab" ON "stock_opname_session_stores" ("uuid") `);
    await queryRunner.query(`CREATE INDEX "IDX_4f4ad1594f376ca0f9b654df1c" ON "stock_opname_session_stores" ("created_at") `);
    await queryRunner.query(`CREATE INDEX "IDX_8d0c42fe8a69e423dd0d33d437" ON "stock_opname_sessions" ("pt_id", "status") `);
    await queryRunner.query(`CREATE INDEX "IDX_678d58b7de91e85a924ce0b92d" ON "auction_batch_assignees" ("id") `);
    await queryRunner.query(`CREATE INDEX "IDX_545f517a5511eff4b76c388413" ON "auction_batch_assignees" ("uuid") `);
    await queryRunner.query(`CREATE INDEX "IDX_853d7f9f28a8ad9cdb66796a37" ON "auction_batch_assignees" ("created_at") `);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" ADD CONSTRAINT "FK_7a14383bff73db93625e4d1d54f" FOREIGN KEY ("so_session_id") REFERENCES "stock_opname_sessions"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" ADD CONSTRAINT "FK_279203cd73a933cd3be9c381599" FOREIGN KEY ("user_id") REFERENCES "users"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" ADD CONSTRAINT "FK_67997ea03f0cbce1962525a285e" FOREIGN KEY ("so_session_id") REFERENCES "stock_opname_sessions"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" ADD CONSTRAINT "FK_48f07ca9023967ba53da8846822" FOREIGN KEY ("pawn_term_id") REFERENCES "pawn_terms"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" ADD CONSTRAINT "FK_452ea0b118f7cd0a631664bf885" FOREIGN KEY ("so_session_id") REFERENCES "stock_opname_sessions"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" ADD CONSTRAINT "FK_18185267142adb82f1d094d6493" FOREIGN KEY ("store_id") REFERENCES "branches"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "spk_records" ADD CONSTRAINT "FK_630cd8bb4d28c9c3ab927bb28dd" FOREIGN KEY ("created_by") REFERENCES "users"("uuid") ON DELETE SET NULL ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ADD CONSTRAINT "FK_eab3ef3234eb2ec49562fd7a03c" FOREIGN KEY ("auction_batch_id") REFERENCES "auction_batches"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ADD CONSTRAINT "FK_49c2f898ef027aa35826e0b1f18" FOREIGN KEY ("user_id") REFERENCES "users"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" DROP CONSTRAINT "FK_49c2f898ef027aa35826e0b1f18"`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" DROP CONSTRAINT "FK_eab3ef3234eb2ec49562fd7a03c"`);
    await queryRunner.query(`ALTER TABLE "spk_records" DROP CONSTRAINT "FK_630cd8bb4d28c9c3ab927bb28dd"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" DROP CONSTRAINT "FK_18185267142adb82f1d094d6493"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" DROP CONSTRAINT "FK_452ea0b118f7cd0a631664bf885"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" DROP CONSTRAINT "FK_48f07ca9023967ba53da8846822"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" DROP CONSTRAINT "FK_67997ea03f0cbce1962525a285e"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" DROP CONSTRAINT "FK_279203cd73a933cd3be9c381599"`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" DROP CONSTRAINT "FK_7a14383bff73db93625e4d1d54f"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_853d7f9f28a8ad9cdb66796a37"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_545f517a5511eff4b76c388413"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_678d58b7de91e85a924ce0b92d"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_8d0c42fe8a69e423dd0d33d437"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_4f4ad1594f376ca0f9b654df1c"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_dd59cce16448f08609fdb8f5ab"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_caf5e1528bcd63f4a4124355b3"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_fdda08535272ae4e96015f5c0a"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_5cbeee10e4650f39fca87f8b72"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_0bbd27131fdab58209de4e4d79"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_e30d49bab27136da3ecefaff75"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_257cccf4450bda5f31c28dd87c"`);
    await queryRunner.query(`DROP INDEX "public"."IDX_c500a38998f9797629996f2a87"`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ALTER COLUMN "user_id" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ALTER COLUMN "auction_batch_id" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ALTER COLUMN "version" SET DEFAULT '1'`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" ALTER COLUMN "store_id" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" ALTER COLUMN "so_session_id" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" ALTER COLUMN "pawn_term_id" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" ALTER COLUMN "so_session_id" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" ALTER COLUMN "user_id" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" ALTER COLUMN "so_session_id" SET NOT NULL`);
    await queryRunner.query(`ALTER TABLE "nkb_records" DROP COLUMN "insurance_fee"`);
    await queryRunner.query(`ALTER TABLE "spk_items" DROP COLUMN "qr_code_print_count"`);
    await queryRunner.query(`ALTER TABLE "spk_items" DROP COLUMN "qr_code_printed_at"`);
    await queryRunner.query(`ALTER TABLE "spk_records" DROP COLUMN "insurance_fee"`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_branches_company_branch_code_not_deleted" ON "branches" ("branch_code", "company_id") WHERE (deleted_at IS NULL)`);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_branches_branch_code_not_deleted" ON "branches" ("branch_code") WHERE (deleted_at IS NULL)`);
    await queryRunner.query(`CREATE INDEX "IDX_auction_batch_assignees_user" ON "auction_batch_assignees" ("user_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_auction_batch_assignees_batch" ON "auction_batch_assignees" ("auction_batch_id") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_sos_stores_session_store" ON "stock_opname_session_stores" ("so_session_id", "store_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_sos_stores_store" ON "stock_opname_session_stores" ("store_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_sos_stores_session" ON "stock_opname_session_stores" ("so_session_id") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_sos_pawn_terms_session_pawn_term" ON "stock_opname_session_pawn_terms" ("so_session_id", "pawn_term_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_sos_pawn_terms_pawn_term" ON "stock_opname_session_pawn_terms" ("pawn_term_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_sos_pawn_terms_session" ON "stock_opname_session_pawn_terms" ("so_session_id") `);
    await queryRunner.query(`CREATE UNIQUE INDEX "IDX_sos_assignees_session_user" ON "stock_opname_session_assignees" ("so_session_id", "user_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_sos_assignees_user" ON "stock_opname_session_assignees" ("user_id") `);
    await queryRunner.query(`CREATE INDEX "IDX_sos_assignees_session" ON "stock_opname_session_assignees" ("so_session_id") `);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ADD CONSTRAINT "FK_auction_batch_assignees_batch" FOREIGN KEY ("auction_batch_id") REFERENCES "auction_batches"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "auction_batch_assignees" ADD CONSTRAINT "FK_auction_batch_assignees_user" FOREIGN KEY ("user_id") REFERENCES "users"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" ADD CONSTRAINT "FK_sos_stores_session" FOREIGN KEY ("so_session_id") REFERENCES "stock_opname_sessions"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_stores" ADD CONSTRAINT "FK_sos_stores_store" FOREIGN KEY ("store_id") REFERENCES "branches"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" ADD CONSTRAINT "FK_sos_pawn_terms_session" FOREIGN KEY ("so_session_id") REFERENCES "stock_opname_sessions"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_pawn_terms" ADD CONSTRAINT "FK_sos_pawn_terms_pawn_term" FOREIGN KEY ("pawn_term_id") REFERENCES "pawn_terms"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" ADD CONSTRAINT "FK_sos_assignees_session" FOREIGN KEY ("so_session_id") REFERENCES "stock_opname_sessions"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE "stock_opname_session_assignees" ADD CONSTRAINT "FK_sos_assignees_user" FOREIGN KEY ("user_id") REFERENCES "users"("uuid") ON DELETE CASCADE ON UPDATE NO ACTION`);
  }
}
